[package]
name    = "netzer"
version = "0.1.0"
edition = "2024"

[features]
default = [ "smol" ] # TODO: Remove
smol    = [ "dep:smol" ]

[lints.rust]
unused_parens = "allow"


[dependencies.smol]
version  = "2.0"
optional = true
